Repository FRONTENDSCHOOL5/final-15-Tripillow, pull requests merged in 2023-06, with the labels that each got.

#13 Design: 이미지 import 경로 변경, 레이아웃 width를 min-width로 변경 (#12)
  src/Components/common/TopNavBar.jsx
Labels: 🎨 마크업 & 스타일링

#26 Feat: Signup 페이지 UI (#18)
  package-lock.json
  src/Components/common/Input.jsx
  src/Pages/Signup.jsx
Labels: ✨ 기능 개발

#27 Fix: Input 포커스시 margin bottom 수정(#28)
  src/Components/common/Input.jsx
Labels: 🐞 버그

#31 Feat: Comment 컴포넌트 추가(#12)
  src/Components/common/Comment.jsx
Labels: ✨ 기능 개발

#35 Design: 공통 컴포넌트 수정(#12)
  src/App.js
  src/Components/common/AlertModal.jsx
  src/Components/common/Navbar.jsx
  src/Components/common/ProductItem.jsx
  src/Components/common/TopNavBar.jsx
  src/Pages/Product.jsx
  src/Pages/Product/Product.jsx
  src/Pages/Product/ProductDetail.jsx
Labels: 🎨 마크업 & 스타일링, 🐞 버그

#45 공통 컴포넌트 기능 추가
  package-lock.json
  src/Components/HomePost/HomePostLayout.jsx
  src/Components/common/CircleButton.jsx
  src/Components/common/Navbar.jsx
  src/Components/common/TopNavBar.jsx
  src/GlobalStyle.jsx
  src/Styles/Layout.jsx
Labels: ✨ 기능 개발

#49 Design: 게시물 상세 페이지 UI(#36)
  src/Components/Comment.jsx
  src/Components/common/PostComment.jsx
  src/Components/common/UploadedPost.jsx
Labels: 🎨 마크업 & 스타일링

#52 공통 컴포넌트 Header 수정 및 기능 추가, 파일 삭제 및 변경
  src/Components/common/BasicHeader.jsx
  src/Components/common/ErrorContents.jsx
  src/Components/common/MainHeader.jsx
  src/Components/common/SearchHeader.jsx
  src/Styles/HeaderLayout.jsx
  src/Styles/TopNavBarLayout.jsx
Labels: ✨ 기능 개발, ♻️ 리팩토링, 🎨 마크업 & 스타일링

#55 공통 컴포넌트 Toggle 버튼 마진값 추가 및 메인 페이지 로고 이미지 추가
  src/Assets/logo-Alphabet.svg
  src/Components/common/Toggle.jsx
Labels: ♻️ 리팩토링, 🎨 마크업 & 스타일링

#57 Refactor: 헤더 경로 변경, 레이아웃 전체 패딩 적용
  package-lock.json
  src/Components/Comment.jsx
  src/Components/HomePost/HomePostLayout.jsx
  src/Components/UploadedPost.jsx
  src/Components/common/Header/BasicHeader.jsx
  src/Components/common/Header/MainHeader.jsx
  src/Components/common/Header/SearchHeader.jsx
  src/Components/common/PostComment.jsx
  src/Pages/Product/Product.jsx
  src/Pages/Product/ProductDetail.jsx
  src/Styles/Layout.jsx
Labels: ✨ 기능 개발, ♻️ 리팩토링, 🎨 마크업 & 스타일링

#61 🚑 HOTFIX: 내부 Layout 좌우 패딩값 삭제, 컴포넌트별 패딩값 적용으로 복구(#60)
  src/Components/Comment.jsx
  src/Components/HomePost/HomePostLayout.jsx
  src/Styles/Layout.jsx
Labels: 🚑 HOTFIX

#62 "Design: 컴포넌트명 변경, NavbarLayout margin값 추가(#12)"
  src/Components/common/Navbar.jsx
  src/Components/common/ProductItem.jsx
  src/Pages/Product/AddProduct.jsx
  src/Pages/Product/Product.jsx
Labels: 🎨 마크업 & 스타일링

#63 Feat: HomePostLayout에서 User컴포넌트 우측 moreBtn 추가, 게시물 업로드 UI 완성
  src/Components/HomePost/HomePostLayout.jsx
  src/Components/UploadedPost.jsx
  src/Components/common/User.jsx
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링

#65 Fix: import한 Header 경로 변경 및 import useNavigate추가
  src/Pages/Product/AddProduct.jsx
  src/Pages/Product/Product.jsx
Labels: 🐞 버그

#67 채팅 페이지
  src/App.js
  src/Pages/Chat/Chat.jsx
  src/Pages/Chat/ChatList.jsx
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링

#77 Route(post) 경로 추가,
  src/App.js
  src/Components/common/Header/UploadHeader.jsx
  src/Pages/Signup.jsx
  src/Pages/UploadPost.jsx
Labels: ♻️ 리팩토링, 🎨 마크업 & 스타일링

#78 Fix: Navbar 내 백틱으로 인한 오류 수정 (#12)
  src/Components/common/Navbar.jsx
Labels: 🐞 버그

#80 프로필 페이지, 공통 컴포넌트
  src/Components/Profile/UserProfile.jsx
  src/Components/Profile/UserProfileSetting.jsx
  src/Components/common/Input.jsx
  src/Pages/Profile.jsx
  src/Utils/UserInfoAPI.jsx
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링

#81 회원가입 페이지
  src/Pages/Signup.jsx
Labels: 🎨 마크업 & 스타일링

#82 Feat: UploadHeader onClick props 추가(#12)
  package-lock.json
  package.json
  src/Components/common/Header/UploadHeader.jsx
  src/Pages/Product/AddProduct.jsx
Labels: ✨ 기능 개발

#84 Home 페이지 버그로 인해 HomePost 태그 제거
  src/Pages/Home.jsx
Labels: 🐞 버그

#86 Search 페이지 마크업 및 검색기능 구현, 버그 수정
  src/App.js
  src/Components/common/Header/SearchHeader.jsx
  src/Pages/Search.jsx
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링, 🐞 버그

#87 Design: HomePostLayout, UserProfile에 background-color 추가 (#12)
  src/Components/HomePost/HomePostLayout.jsx
  src/Components/Profile/UserProfile.jsx
Labels: 🎨 마크업 & 스타일링

#89 HomePostLayout, UserProfile, Profile
  src/Components/HomePost/HomePostLayout.jsx
  src/Components/Profile/UserProfile.jsx
  src/Pages/Profile.jsx
Labels: 🎨 마크업 & 스타일링

#90 공통 컴포넌트 홈포스트 스켈레톤 UI
  src/Components/HomePost/HomePostSkeleton.jsx
  src/Styles/SkeletonItem.jsx
Labels: 🎨 마크업 & 스타일링

#91 게시물 업로드하기
  src/Pages/UploadPost.jsx
Labels: ✨ 기능 개발

#92 CircleButton 기본 이미지 업로드 문제 해결, ImgUploadAPI 함수 분리
  src/Assets/icons/upload.svg
  src/Components/common/CircleButton.jsx
  src/Pages/Product/Product.jsx
  src/Pages/UploadPost.jsx
Labels: ✨ 기능 개발, ♻️ 리팩토링

#93 Navbar active 아이콘 수정(#12)
  src/Components/common/Navbar.jsx
  src/Pages/Product/AddProduct.jsx
Labels: 🐞 버그

#94 프로필 페이지, 공통 컴포넌트 ProductItem, 회원가입 페이지
  src/Components/common/ProductItem.jsx
  src/Pages/Profile.jsx
  src/Pages/Signup.jsx
  src/Utils/ProductListAPI.jsx
Labels: ✨ 기능 개발

#95 공통 컴포넌트, 프로필 페이지
  src/Components/HomePost/HomePostLayout.jsx
  src/Components/Profile/UserProfile.jsx
  src/Components/common/User.jsx
Labels: ✨ 기능 개발

#97 검색 페이지 검색시 디바운스 기능, 로딩시 스켈레톤UI 추가
  src/Pages/Search.jsx
Labels: ✨ 기능 개발

#96 Post 이미지의 close버튼 추가
  src/App.js
  src/Pages/Post.jsx
  src/Utils/ImageUploadAPI.jsx
  src/Utils/validate.js
Labels: ✨ 기능 개발

#98 HomePostSkeleton내 UserSkeleton 컴포넌트화, 경로 변경
  src/Components/common/Skeleton/HomePostSkeleton.jsx
  src/Components/common/Skeleton/UserSkeleton.jsx
Labels: ♻️ 리팩토링

#99 Skeleton폴더 내 파일 경로 변경
  src/Components/common/Skeleton/HomePostSkeleton.jsx
  src/Components/common/Skeleton/UserSkeleton.jsx
Labels: 🐞 버그

#100 홈페이지 피드 가져오는 API 추가, 무한스크롤 적용, 첫 로딩시 스켈레톤 UI 적용
  src/Pages/Home.jsx
Labels: ✨ 기능 개발, 🐞 버그

#101 공통 컴포넌트 Basic Header
  src/Components/common/AlertModal.jsx
  src/Components/common/Header/BasicHeader.jsx
  src/Components/common/Modal.jsx
Labels: ✨ 기능 개발

#103 App.js 경로 변경 및 Product 페이지 기능 추가(#14)
  src/App.js
  src/Components/common/Navbar.jsx
  src/Components/common/ProductItem.jsx
  src/Pages/Product/AddProduct.jsx
  src/Pages/Product/Product.jsx
  src/Pages/Product/ProductDetail.jsx
  src/Utils/ProductDetailAPI.jsx
Labels: ✨ 기능 개발

#106 홈페이지 내 디폴트페이지 추가, 로딩 기능 리팩토링
  src/Pages/Home.jsx
Labels: ✨ 기능 개발, ♻️ 리팩토링

#107 HOTFIX: 상품 삭제 기능 오류 발생
  src/Components/common/Header/BasicHeader.jsx
  src/Pages/Product/ProductDetail.jsx
  src/Utils/ProductDeleteAPI.jsx
Labels: 🐞 버그

#108 Product Detail 페이지
  src/Components/common/Header/BasicHeader.jsx
  src/Utils/ProductDeleteAPI.jsx
Labels: ✨ 기능 개발

#110 프로필 페이지, 프로필 관련 API
  src/App.js
  src/Components/Profile/UserProfile.jsx
  src/Components/Profile/UserProfileSetting.jsx
  src/Components/common/Header/UploadHeader.jsx
  src/Hooks/HooksSample.jsx
  src/Pages/Profile.jsx
  src/Utils/EditProfileAPI.jsx
  src/Utils/UserInfoAPI.jsx
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링

#111 Product 기능 구현(#14)
  src/Components/common/ProductItem.jsx
  src/Pages/Product/AddProduct.jsx
  src/Pages/Product/Product.jsx
  src/Pages/Product/ProductDetail.jsx
  src/Pages/Product/ProductModification.jsx
  src/Utils/ProductDeleteAPI.jsx
  src/Utils/ProductDetailAPI.jsx
  src/Utils/ProductListAPI.jsx
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링, 🐞 버그

#113 AddProduct 상세 설명란 추가 및 스타일 지정(#14)
  src/Pages/Product/AddProduct.jsx
  src/Pages/Product/ProductDetail.jsx
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링, 🐞 버그

#115 홈페이지 로딩 스피너 추가 및 버그 수정, 공통컴포넌트 로딩스피너 추가
  src/Assets/icons/loading-spinner.png
  src/Components/common/Spinner.jsx
  src/Pages/Home.jsx
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링, 🐞 버그

#116 공톰 컴포넌트 LoginMethod 추가
  src/Assets/icons/email.svg
  src/Components/LoginMethod.jsx
  src/Components/common/SnsButton.jsx
Labels: ♻️ 리팩토링, 🎨 마크업 & 스타일링

#118 검색페이지 결과 모두 보기 버튼 추가
  src/Pages/Search.jsx
Labels: ✨ 기능 개발

#119 상품 페이지, Hook
  src/Hooks/useFetch.jsx
  src/Hooks/useInput.jsx
  src/Pages/Product/Product.jsx
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링

#120 Modal 수정 버튼 클릭 시 상품 수정페이지로 이동
  src/Components/common/Header/BasicHeader.jsx
  src/Components/common/Modal.jsx
  src/Components/common/ProductItem.jsx
  src/Pages/Product/ProductDetail.jsx
  src/Pages/Product/ProductModification.jsx
  src/Utils/ProductDeleteAPI.jsx
  src/Utils/ProductModifyAPI.jsx
Labels: ✨ 기능 개발, 🐞 버그

#124 상품페이지 무한스크롤 구현 및 리팩토링, 홈페이지 내 중복 요소 제거
  src/Components/common/Skeleton/ProductItemSkeleton.jsx
  src/Pages/Home.jsx
  src/Pages/Product/Product.jsx
Labels: ✨ 기능 개발, ♻️ 리팩토링, 🎨 마크업 & 스타일링

#127 상품 페이지 내 버그 수정, 채팅 페이지 수정
  src/App.js
  src/Pages/Chat/Chat.jsx
  src/Pages/Chat/ChatDetail.jsx
  src/Pages/Chat/ChatList.jsx
  src/Pages/Chat/ChatLists.json
  src/Pages/Chat/ChatUser.jsx
  src/Pages/Product/Product.jsx
Labels: ✨ 기능 개발, ♻️ 리팩토링, 🎨 마크업 & 스타일링, 🐞 버그

#131 프로필페이지 공통컴포넌트
  src/Components/Profile/UserProfile.jsx
  src/Components/common/AlertTop.jsx
  src/Components/common/FollowUser.jsx
  src/Pages/Followers.jsx
  src/Pages/Profile.jsx
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링

#134 Modal, ProductDetail
  src/Components/PostModal.jsx
  src/Components/common/Modal.jsx
  src/Pages/Product/ProductDetail.jsx
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링

#137 프로필 페이지, 채팅 페이지, 회원가입 페이지
  src/App.js
  src/Assets/icons/icon-img-layers.svg
  src/Components/HomePost/HomePostLayout.jsx
  src/Components/HomePost/ViewImage.jsx
  src/Components/Profile/UserProfile.jsx
  src/Pages/Chat/Chat.jsx
  src/Pages/Chat/ChatDetail.jsx
  src/Pages/Chat/ChatLists.json
  src/Pages/Chat/ChatUser.jsx
  src/Pages/Chat/chatLists.js
  src/Pages/Profile.jsx
  src/Pages/Signup.jsx
  src/test/images.js
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링, 🐞 버그

#140 Fix: PostModal props 전달 오류 수정
  src/Components/PostModal.jsx
Labels: 🐞 버그

#141 랜딩페이지, App.js
  src/App.js
  src/Components/common/AlertTop.jsx
  src/Pages/Landing.jsx
  src/Utils/ProtectRoute/ProtectRoute.jsx
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링

#142 Product 페이지 렌더링 방식 변경 및 리팩토링
  src/Pages/Home.jsx
  src/Pages/Product/Product.jsx
Labels: ♻️ 리팩토링

#144 검색 페이지 검색 결과 하이라이팅 기능 및 유저 컴포넌트 리팩토링
  src/Components/common/User.jsx
  src/Pages/Search.jsx
Labels: ✨ 기능 개발

#145 설정페이지
  src/App.js
  src/Components/common/AlertModal.jsx
  src/Components/common/Header/BasicHeader.jsx
  src/Components/common/Modal.jsx
  src/Pages/Setting.jsx
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링

#146 User 컴포넌트 ProductDetail 페이지에서 오류나는 현상 수정
  src/Components/common/User.jsx
Labels: 🐞 버그

#147 게시물 상세페이지
  src/Components/Comment.jsx
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링

#148 상품페이지
  src/Components/common/ProductItem.jsx
Labels: ♻️ 리팩토링, 🐞 버그

#149 PostImage 컴포넌트 분리, 이미지 없을 경우 heart, comment를 게시글 하단에 오게 배치(#102)
  src/Components/Comment.jsx
  src/Components/HomePost/HomePostLayout.jsx
  src/Components/PostModal.jsx
  src/Components/common/PostImage.jsx
Labels: ✨ 기능 개발, ♻️ 리팩토링, 🎨 마크업 & 스타일링, 🐞 버그

#151 프로필 페이지
  src/Pages/Profile.jsx
  src/Utils/FollowAPI.jsx
Labels: 🐞 버그

#152 ProductDetail 줄바꿈 표시되게 수정(#14)
  src/Pages/Product/ProductDetail.jsx
Labels: 🐞 버그

#153 홈페이지 탑버튼 애니메이션 추가 및 아이콘 변경, 스크롤에 따라 탑버튼 나타나게 수정
  src/Assets/icons/topbutton.svg
  src/Components/common/Topbutton.jsx
  src/Pages/Home.jsx
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링

#154 🚑HOTFIX: 게시물 상세페이지 접근시 오류 해결입니다
  src/Components/Comment.jsx
  src/Components/HomePost/HomePostLayout.jsx
  src/Pages/PostDetail.jsx
Labels: 🚑 HOTFIX

#156 모달 뒷배경 추가로 다른 동작 방지, 게시글 수정시 이미지 불러오는 문제 해결
  src/Components/Comment.jsx
  src/Components/CommentModal.jsx
  src/Components/HomePost/HomePostLayout.jsx
  src/Components/PostModal.jsx
  src/Components/common/AlertModal.jsx
  src/Components/common/Header/BasicHeader.jsx
  src/Components/common/Modal.jsx
  src/Components/common/PostAlertModal.jsx
  src/Pages/PostModification.jsx
Labels: ✨ 기능 개발, 🐞 버그

#157 설정 및 개인정보
  src/Components/common/Header/BasicHeader.jsx
  src/Pages/Setting.jsx
Labels: ♻️ 리팩토링

#158 게시글/댓글 신고시 TopModal 추가(#139)
  src/Components/Comment.jsx
  src/Components/HomePost/HomePostLayout.jsx
  src/Components/common/AlertTop.jsx
Labels: ✨ 기능 개발

#162 게시글 댓글 여러개일 경우 최신순 5개씩 표시(#102)
  src/Components/Comment.jsx
  src/Components/common/PostComment.jsx
  src/Pages/Post.jsx
  src/Pages/PostDetail.jsx
  src/Utils/GetNumerousCommentAPI.jsx
Labels: ✨ 기능 개발

#164 프로필페이지
  src/Components/HomePost/ViewImage.jsx
  src/Pages/Profile.jsx
Labels: ♻️ 리팩토링

#163 Feat: 상품 디테일 페이지에서 더보기 버튼 삭제(#14)
  src/Pages/Product/Product.jsx
  src/Pages/Product/ProductDetail.jsx
Labels: ✨ 기능 개발

#165 공통 컴포넌트 BasicHeader 내 요소 수직 중앙정렬
  src/Components/common/Header/BasicHeader.jsx
Labels: 🎨 마크업 & 스타일링

#166 Refactor
  public/index.html
  src/Components/Profile/UserProfile.jsx
  src/Components/common/Input.jsx
  src/Components/common/PostComment.jsx
  src/GlobalStyle.jsx
  src/Pages/Chat/ChatDetail.jsx
  src/Pages/Login.jsx
Labels: ♻️ 리팩토링

#167 홈페이지 스피너 끝나면 위로 조금 이동할 때 이동 방식 리팩토링
  src/Pages/Home.jsx
Labels: ♻️ 리팩토링

#170 ProductDetail 수정/삭제 권한 변경(#14)
  src/Pages/Chat/Chat.jsx
  src/Pages/Product/Product.jsx
  src/Pages/Product/ProductDetail.jsx
Labels: ✨ 기능 개발

#172 Fix: 카테고리 기능 활성화 후 게시물 이미지 수정 문제(#169)
  src/Pages/PostModification.jsx
Labels: 🐞 버그

#174 랜딩페이지
  src/Components/LoginMethod.jsx
  src/Pages/Landing.jsx
Labels: ✨ 기능 개발

#175 랜딩페이지
  src/Pages/Landing.jsx
Labels: 🎨 마크업 & 스타일링

#176 Followers 페이지 헤더부분 버그 수정
  src/Pages/Followers.jsx
Labels: 🐞 버그

#184 검색 페이지 setTimeout 제거
  src/Pages/Search.jsx
Labels: ✨ 기능 개발

#182 홈 페이지
  src/Components/common/Header/BasicHeader.jsx
  src/Components/common/Toggle.jsx
  src/Pages/Home.jsx
  src/Recoil/whichCountry/whichCountry.js
Labels: ✨ 기능 개발

#185 Rename: 중복 파일 삭제
  src/Components/common/Header/BasicHeader.jsx
  src/Components/common/Modal.jsx
Labels: 📃 문서 수정

#186 모달 애니메이션 추가, AlertTop 모달 중첩 문제 해결
  src/Components/Comment/CommentModal.jsx
  src/Components/PostModal.jsx
  src/Components/common/Modal/AlertTop.jsx
  src/Components/common/Modal/Modal.jsx
Labels: ✨ 기능 개발, 🐞 버그

#187 회원가입 페이지
  src/Pages/Signup.jsx
Labels: 🐞 버그

#189 홈 페이지
  src/Components/common/Toggle.jsx
  src/Pages/Home.jsx
Labels: 🐞 버그

#188 검색 페이지 계정 검색 시 레이아웃을 뚫고 나가는 현상 수정
  src/Components/common/Skeleton/ProductItemSkeleton.jsx
  src/Components/common/User.jsx
  src/Pages/Home.jsx
Labels: 🐞 버그
