Repository FRONTENDSCHOOL5/final-15-Tripillow, pull requests merged in 2023-07, with the labels that each got.

#194 검색 페이지 이미지 예외처리 위해 User컴포넌트 수정
  src/Components/common/User.jsx
Labels: ♻️ 리팩토링

#196 Refactor#195
  src/App.js
  src/Components/LoginMethod.jsx
  src/Components/common/Header/BasicHeader.jsx
  src/Components/common/Navbar.jsx
  src/GlobalStyle.jsx
  src/Pages/Home.jsx
  src/Pages/Post/PostDetail.jsx
  src/Pages/Product/AddProduct.jsx
  src/Pages/Product/Product.jsx
  src/Pages/Product/ProductDetail.jsx
  src/Pages/Profile/Followers.jsx
  src/Pages/Profile/Profile.jsx
  src/Recoil/whichView/whichView.js
  src/Styles/Layout.jsx
Labels: ♻️ 리팩토링

#198 최상단 height 변경으로 border가 더 나타나지않는 현상 Layout 내부 Scroll 생성으로 수정(#195)
  src/Components/LoginMethod.jsx
  src/GlobalStyle.jsx
  src/Pages/Home.jsx
  src/Pages/Post/PostDetail.jsx
  src/Pages/Product/Product.jsx
  src/Pages/Profile/Profile.jsx
  src/Styles/Layout.jsx
Labels: ♻️ 리팩토링

#199 HOTFIX: 사용하지 않는 스타일 컴포넌트 태그 삭제
  src/Components/common/Navbar.jsx
  src/Pages/Product/ProductDetail.jsx
  src/Pages/Profile/Profile.jsx
Labels: 🚑 HOTFIX

#200 Post 이미지 압축 기능 추가
  package-lock.json
  package.json
  src/Pages/Post/Post.jsx
  src/Pages/Post/PostModification.jsx
  src/Utils/validate.js
Labels: ♻️ 리팩토링

#204 프로필 앨범보기 사진 배열 첫번째 사진으로 바꾸기
  src/Components/HomePost/ViewImage.jsx
Labels: ♻️ 리팩토링

#208 모바일에서 HomePost 이미지 제스쳐로 넘기기
  src/Components/common/PostImage.jsx
Labels: ✨ 기능 개발, ♻️ 리팩토링

#218 Design: 이미지 슬라이드 첫번째와, 마지막 이미지에는 없애기
  src/Components/common/PostImage.jsx
Labels: 🎨 마크업 & 스타일링

#220 이미지 클릭시 모달창으로 원본 띄우기
  src/Components/HomePost/HomePostLayout.jsx
  src/Components/common/Modal/ImageModal.jsx
  src/Components/common/PostImage.jsx
Labels: ✨ 기능 개발

#221 Feat: 상품 탭에서 상품/외화 선택 기능 추가
  src/Components/common/ProductItem.jsx
  src/Pages/Product/AddProduct.jsx
  src/Pages/Product/Product.jsx
  src/Pages/Product/ProductDetail.jsx
  src/Pages/Product/ProductModification.jsx
  src/Utils/ProductModifyAPI.jsx
Labels: ✨ 기능 개발

#222 상품 등록페이지에서 이미지 미등록시 저장 버튼 비활성화, Layout border 수정
  src/Pages/Product/AddProduct.jsx
  src/Pages/Product/ProductModification.jsx
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링, 🐞 버그

#224 로그인 input focus, 랜딩페이지 스타일드 컴포넌트 에러, 채팅 상세 페이지
  src/Components/LoginMethod.jsx
  src/Pages/Chat/Chat.jsx
  src/Pages/Chat/ChatDetail.jsx
  src/Pages/Chat/ChatUser.jsx
  src/Pages/Login.jsx
  src/Pages/Signup.jsx
Labels: bug, ✨ 기능 개발

#227 Feat: Product Detail에서 사진 클릭 시 원본 사진 모달로 띄우기
  src/Pages/Product/ProductDetail.jsx
Labels: ✨ 기능 개발

#232 Feat: PC 버전 NavBar 컴포넌트 추가
  src/Assets/character.svg
  src/Assets/icons/icon-search-fill.svg
  src/Components/PCNav/PCNavBar.jsx
  src/Pages/Chat/Chat.jsx
  src/Pages/Product/Product.jsx
Labels: ✨ 기능 개발, 🐞 버그
