Repository FRONTENDSCHOOL5/final-15-Tripillow, pull requests merged in 2023-08, with the labels that each got.

#235 [프로필, Modal] 상시 에러 수정
  src/Components/common/Modal/Modal.jsx
  src/Pages/Profile/Profile.jsx
Labels: 🐞 버그

#237 Refactor: PC NavBar 모듈화
  src/Components/PCNav/useIsDesktop.jsx
  src/Pages/Chat/Chat.jsx
  src/Pages/Home.jsx
  src/Pages/Post/Post.jsx
  src/Pages/Product/Product.jsx
  src/Pages/Profile/Profile.jsx
Labels: ♻️ 리팩토링

#239 Border 삭제, Scroll 윈도우 기준
  src/Components/common/Navbar.jsx
  src/Pages/Home.jsx
  src/Pages/Product/Product.jsx
  src/Pages/Profile/Profile.jsx
  src/Styles/HeaderLayout.jsx
  src/Styles/Layout.jsx
Labels: ♻️ 리팩토링

#240 팔로우,팔로잉 페이지 Layout 변경
  src/Pages/Profile/Followers.jsx
Labels: 🎨 마크업 & 스타일링

#242 Refactor: 페이지 새로고침 후 resize 시에만 PC NavBar 컴포넌트가 보이는 오류 수정
  src/App.js
  src/Components/PCNav/useIsDesktop.jsx
  src/Pages/Chat/Chat.jsx
  src/Pages/Home.jsx
  src/Pages/Post/Post.jsx
  src/Pages/Product/Product.jsx
  src/Pages/Product/ProductDetail.jsx
  src/Pages/Profile/Profile.jsx
Labels: ♻️ 리팩토링, 🎨 마크업 & 스타일링

#254 홈페이지 내 새글 불러오기 오류나는 현상 수정 및 누락된 수정사항 보완
  src/Pages/Home.jsx
Labels: 🐞 버그

#255 My pillowers 컴포넌트 생성
  src/Components/Home/MyPillowers.jsx
  src/Components/common/FollowUser.jsx
  src/Pages/Home.jsx
Labels: ✨ 기능 개발, ♻️ 리팩토링

#256 Feat: 상품/외화 카테고리 저장
  src/Components/common/ProductItem.jsx
  src/Pages/Product/Product.jsx
  src/Recoil/productCategory/productCategory.js
Labels: ✨ 기능 개발

#258 프로필 페이지 PC 버전
  src/Components/Profile/MobileUser.jsx
  src/Components/Profile/PCUser.jsx
  src/Components/Profile/UserProfile.jsx
  src/Components/Profile/UserStyle.jsx
  src/Components/UserProfile.jsx
  src/Pages/Profile/Profile.jsx
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링

#259 PC버전 헤더 대응, 채팅 PC, 업로드 PC
  src/Pages/Chat/Chat.jsx
  src/Pages/Chat/ChatDetail.jsx
  src/Pages/Chat/ChatUser.jsx
  src/Pages/Home.jsx
  src/Pages/Post/Post.jsx
  src/Pages/Post/PostDetail.jsx
  src/Pages/Post/PostModification.jsx
  src/Pages/Product/AddProduct.jsx
  src/Pages/Product/Product.jsx
  src/Pages/Product/ProductDetail.jsx
  src/Pages/Product/ProductModification.jsx
  src/Pages/Profile/Followers.jsx
  src/Pages/Profile/Profile.jsx
  src/Pages/Profile/Setting.jsx
  src/Pages/Profile/UserProfileSetting.jsx
Labels: ✨ 기능 개발

#267 라우터 분리, MyPillowings 보여주기 및 이름변경
  src/App.js
  src/Components/Home/MyPillowings.jsx
  src/Pages/Home.jsx
  src/Router/AppRoutes.jsx
Labels: ✨ 기능 개발

#268 PC 랜딩페이지, PC 로그인페이지, App.js
  src/App.js
  src/Assets/pc_facebook.png
  src/Assets/pc_google.png
  src/Assets/pc_kakao.png
  src/Components/Landing/Landings.jsx
  src/Components/Landing/PCTripillow.jsx
  src/Components/Login/LoginForm.jsx
  src/Components/Login/PCLogin.jsx
  src/Pages/Landing.jsx
  src/Pages/Login.jsx
  src/Styles/LandingAnimation.jsx
  src/Utils/Login/LoginFunc.jsx
Labels: ✨ 기능 개발

#270 useLocation사용으로 인한 useQuery refetch 현상 수정
  src/App.js
  src/Components/Home/MyPillowings.jsx
  src/Pages/Home.jsx
  src/Pages/Post/Post.jsx
  src/Pages/Post/PostDetail.jsx
  src/Pages/Post/PostModification.jsx
  src/Pages/Product/AddProduct.jsx
  src/Pages/Product/Product.jsx
  src/Pages/Product/ProductDetail.jsx
  src/Pages/Product/ProductModification.jsx
  src/Pages/Profile/Followers.jsx
  src/Pages/Profile/Profile.jsx
  src/Pages/Profile/UserProfileSetting.jsx
Labels: ✨ 기능 개발, 🐞 버그

#272 Feat: 상품 페이지 이미지 최적화
  src/Pages/Product/AddProduct.jsx
  src/Pages/Product/ProductDetail.jsx
  src/Utils/ImageUploadAPI.jsx
Labels: ✨ 기능 개발, ♻️ 리팩토링

#273 Feat: PC버전 검색창 추가 및 검색창 내 유저 클릭 범위 변경(#263)
  src/Components/PCNav/PCNavBar.jsx
  src/Components/common/Header/SearchHeader.jsx
  src/Components/common/Modal/PCNavbarModal.jsx
  src/Components/common/User.jsx
  src/Pages/Search.jsx
Labels: ✨ 기능 개발, ♻️ 리팩토링

#275 PCNav 랜딩,로그인,회원가입 페이지에서 제외
  src/App.js
  src/Router/AppRoutes.jsx
Labels: 🐞 버그

#278 채팅, 채팅상세 페이지
  src/Components/Chat/ChatContent.jsx
  src/Components/Chat/ChatList.jsx
  src/Components/Chat/ChatUser.jsx
  src/Components/Chat/PCChat.jsx
  src/Components/common/Header/BasicHeader.jsx
  src/Hooks/useFollowing.jsx
  src/Pages/Chat/Chat.jsx
  src/Pages/Chat/ChatDetail.jsx
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링

#282 Bug: User 내 더보기 버튼 누를 시 프로필로 이동되는 버그 수정 (#281)
  src/Components/common/User.jsx
Labels: 🐞 버그

#284 상품상세에서 채팅하기 버튼 위치 수정
  src/Pages/Product/ProductDetail.jsx
Labels: 🎨 마크업 & 스타일링

#285 잘못된 접근시 로그인페이지, PC토스트
  src/Components/Landing/Landings.jsx
  src/Components/Sign/LoginForm.jsx
  src/Components/common/Modal/AlertTop.jsx
  src/Components/common/Modal/PCToast.jsx
  src/Utils/ProtectRoute/ProtectRoute.jsx
Labels: ✨ 기능 개발, ♻️ 리팩토링, 🎨 마크업 & 스타일링

#290 PC 상품 디테일 더보기 버튼(수정, 삭제) 추가
  src/Assets/icons/icon-more-pc.svg
  src/Pages/Product/ProductDetail.jsx
Labels: ✨ 기능 개발

#291 프로필 페이지 컴포넌트 분리, useQuery 사용
  src/Components/Profile/ProfileMain.jsx
  src/Components/Profile/ProfileView.jsx
  src/Components/common/Skeleton/ProfileSkeleton.jsx
  src/Pages/Profile/Profile.jsx
  src/Utils/GetPostAPI.jsx
  src/Utils/MyInfoAPI.jsx
  src/Utils/ProductListAPI.jsx
  src/Utils/UserInfoAPI.jsx
Labels: ✨ 기능 개발, ♻️ 리팩토링

#293 프로필 페이지 재사용 함수 및 상태 분리, drilling 방지, 모달 새로고침시 안나오게 수정
  package-lock.json
  src/Components/Profile/MobileUser.jsx
  src/Components/Profile/PCUser.jsx
  src/Components/Profile/ProfileMain.jsx
  src/Components/Profile/UserProfile.jsx
  src/Hooks/useUserProfile.jsx
  src/Pages/Profile/Profile.jsx
  src/Recoil/followPath/followPath.js
  src/Utils/GetPostAPI.jsx
  src/Utils/UserInfoAPI.jsx
Labels: ✨ 기능 개발

#295 Refactor: useSetRecoilState로 사용하지 않는recoil 변수 삭제
  src/Components/common/Modal/PCAlertModal.jsx
Labels: ♻️ 리팩토링

#301 이미지 업로드 에러 수정
  src/Components/Sign/SignupForm.jsx
  src/Hooks/Sign/useSignup.jsx
  src/Pages/Profile/UserProfileSetting.jsx
  src/Utils/uploadFile.js
Labels: ✨ 기능 개발, 🐞 버그
