Repository FRONTENDSCHOOL5/final-15-Tripillow, pull requests merged in 2023-09, with the labels that each got.

#303 MyInfoAPI response 받아오는 방식 수정, husky 추가, ESLint 에러 수정
  .github/ISSUE_TEMPLATE/♻️-refactor-.md
  .github/ISSUE_TEMPLATE/✨-feature-.md
  .github/ISSUE_TEMPLATE/🐞-bug-.md
  .github/pull_request_template.md
  .husky/pre-commit
  .husky/pre-push
  README.md
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/Components/Chat/ChatContent.jsx
  src/Components/Chat/ChatUser.jsx
  src/Components/Comment/Comment.jsx
  src/Components/Landing/Landings.jsx
  src/Components/Landing/PCTripillow.jsx
  src/Components/PCNav/PCNavBar.jsx
  src/Components/PCNav/useIsDesktop.jsx
  src/Components/Profile/ProfileMain.jsx
  src/Components/Sign/LoginForm.jsx
  src/Components/TabNav/TabNavBar.jsx
  src/Components/common/Button.jsx
  src/Components/common/CircleButton.jsx
  src/Components/common/FollowUser.jsx
  src/Components/common/Header/BasicHeader.jsx
  src/Components/common/Modal/ImageModal.jsx
  src/Components/common/Modal/PCModal.jsx
  src/Components/common/Modal/PCNavbarModal.jsx
  src/Components/common/Navbar.jsx
  src/Components/common/PostComment.jsx
  src/Components/common/ProductItem.jsx
  src/Components/common/Toggle.jsx
  src/Hooks/Sign/useLogin.jsx
  src/Hooks/Sign/useSignup.jsx
  src/Hooks/useFollowing.jsx
  src/Pages/Post/PostDetail.jsx
  src/Pages/Post/PostModification.jsx
  src/Pages/Product/AddProduct.jsx
  src/Pages/Product/ProductDetail.jsx
  src/Pages/Profile/Followers.jsx
  src/Pages/Profile/Profile.jsx
  src/Pages/Profile/Setting.jsx
  src/Pages/Profile/UserProfileSetting.jsx
  src/Pages/Search.jsx
  src/Pages/Signup.jsx
  src/Recoil/isDesktop/isDesktop.js
  src/Recoil/isTab/isTab.js
  src/Recoil/productCategory/productCategory.js
  src/Utils/EditProfileAPI.jsx
  src/Utils/FollowingListAPI.jsx
  src/Utils/GetNumerousCommentAPI.jsx
  src/Utils/MyInfoAPI.jsx
  src/Utils/ProductDetailAPI.jsx
  src/Utils/ProtectRoute/ProtectRoute.jsx
  src/Utils/validate.js
  src/index.js
Labels: ♻️ 리팩토링

#308 useIsDesktop 추가, 로그아웃시 이동 페이지 수정
  src/App.js
  src/Components/common/Modal/PCAlertModal.jsx
Labels: ♻️ 리팩토링

#310 PC NavBar, Tab NavBar nav 태그로 수정, 이미지 alt 입력 및 useEffect 의존성 배열 메모이제이션
  src/Components/PCNav/PCNavBar.jsx
  src/Components/TabNav/TabNavBar.jsx
Labels: ♻️ 리팩토링

#311 Bug: 홈페이지 스크롤 최하단 도달 후 새 페이지 불러올때 오류, 팔로우 목록 없을 때 Empty페이지 안 뜨는 버그 수정 (#307)
  src/Pages/Home.jsx
Labels: 🐞 버그

#312 검색페이지
  src/Components/PCNav/PCNavBar.jsx
  src/Pages/Search.jsx
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링, 🐞 버그

#313 컴포넌트에 버튼 aria-label, 이미지 alt 추가
  src/Components/PCNav/PCNavBar.jsx
  src/Components/TabNav/TabNavBar.jsx
  src/Components/common/Button.jsx
  src/Components/common/CircleButton.jsx
  src/Components/common/Header/BasicHeader.jsx
  src/Components/common/Header/UploadHeader.jsx
  src/Components/common/Navbar.jsx
  src/Components/common/ProductItem.jsx
  src/Components/common/Toggle.jsx
  src/Pages/Product/AddProduct.jsx
  src/Pages/Product/ProductDetail.jsx
  src/Pages/Product/ProductModification.jsx
Labels: ♻️ 리팩토링

#316 모바일 h1 태그 추가
  src/Components/Chat/ChatContent.jsx
  src/Components/Landing/Landings.jsx
  src/Components/Landing/PCTripillow.jsx
  src/Components/Profile/MobileUser.jsx
  src/Components/Profile/PCUser.jsx
  src/Components/Profile/UserProfile.jsx
  src/Components/Sign/PCSign.jsx
  src/Components/common/Header/BasicHeader.jsx
  src/Components/common/Header/MainHeader.jsx
  src/Components/common/Header/SearchHeader.jsx
  src/Components/common/Header/UploadHeader.jsx
  src/Components/common/User.jsx
  src/Hooks/useUserProfile.jsx
  src/Pages/Chat/Chat.jsx
  src/Pages/NotFound.jsx
  src/Pages/Post/PostDetail.jsx
  src/Pages/Product/AddProduct.jsx
  src/Pages/Product/ProductDetail.jsx
  src/Pages/Profile/Followers.jsx
  src/Pages/Profile/Profile.jsx
  src/Pages/Profile/Setting.jsx
  src/Pages/Search.jsx
  src/Styles/UserStyle.jsx
Labels: ♻️ 리팩토링

#320 ProudctDetail 렌더싱 시 undefined가 잠깐 나오는 현상/가격 줄바꿈 현상 수정 및 eslint 오류 해결
  src/Api/Product/ProductDetailAPI.jsx
  src/Pages/Product/ProductDetail.jsx
Labels: ♻️ 리팩토링, 🐞 버그

#325 검색 페이지
  src/Components/SideNav/SideNavBar.jsx
  src/Components/common/Header/SearchHeader.jsx
  src/Pages/Search.jsx
  src/Pages/Search/Search.jsx
  src/Pages/Search/SearchContent.jsx
  src/Pages/Search/SearchModal.jsx
  src/Router/AppRoutes.jsx
Labels: ♻️ 리팩토링, 🐞 버그

#326 Button aria-label, Meta Tag 추가
  package-lock.json
  package.json
  public/index.html
  src/Components/Chat/ChatContent.jsx
  src/Components/Comment/Comment.jsx
  src/Components/Comment/CommentModal.jsx
  src/Components/Home/MyPillowings.jsx
  src/Components/HomePost/HomePostLayout.jsx
  src/Components/PostModal.jsx
  src/Components/Profile/ProfileView.jsx
  src/Components/common/MetaTag.jsx
  src/Components/common/PostImage.jsx
  src/Components/common/User.jsx
  src/Pages/Chat/Chat.jsx
  src/Pages/Home.jsx
  src/Pages/Landing.jsx
  src/Pages/Login.jsx
  src/Pages/Post/Post.jsx
  src/Pages/Post/PostDetail.jsx
  src/Pages/Post/PostModification.jsx
  src/Pages/Product/Product.jsx
  src/Pages/Profile/Profile.jsx
  src/Pages/Profile/Setting.jsx
  src/Pages/Search.jsx
  src/Pages/Search/Search.jsx
  src/Pages/Signup.jsx
  src/index.js
Labels: ♻️ 리팩토링

#330 ESLint 에러 처리 (#329)
  src/Components/Sign/LoginForm.jsx
  src/Components/common/PostComment.jsx
  src/Hooks/Sign/useLogin.jsx
  src/Pages/Product/AddProduct.jsx
Labels: 🐞 버그

#332 Fix: 상품 삭제 버튼 클릭 시, 모달 배경이 겹치는 현상 수정
  src/Pages/Product/ProductDetail.jsx
Labels: 🐞 버그

#333 에러 수정 및 리팩토링
  src/Components/SideNav/SideNavBar.jsx
  src/Pages/Home.jsx
  src/Pages/Search.jsx
  src/Pages/Search/SearchContent.jsx
Labels: ♻️ 리팩토링, 🐞 버그

#334 이미지 압축, 프로필 수정
  public/index.html
  src/Api/Upload/CompressedImageUploadAPI.jsx
  src/Components/Sign/LoginForm.jsx
  src/Components/Sign/SignupForm.jsx
  src/Components/common/PostImage.jsx
  src/Pages/Post/Post.jsx
  src/Pages/Post/PostModification.jsx
  src/Pages/Product/AddProduct.jsx
  src/Pages/Product/ProductModification.jsx
  src/Pages/Profile/Profile.jsx
  src/Pages/Profile/UserProfileSetting.jsx
  src/Utils/uploadFile.js
Labels: ✨ 기능 개발, ♻️ 리팩토링, 🐞 버그

#337 aria-label 추가
  src/Components/Search/SearchContent.jsx
  src/Components/Search/SearchModal.jsx
  src/Components/SideNav/SideNavBar.jsx
  src/Components/common/Header/MainHeader.jsx
  src/Components/common/Header/SearchHeader.jsx
  src/Components/common/Topbutton.jsx
  src/Components/common/User.jsx
  src/Pages/Search.jsx
  src/Router/AppRoutes.jsx
Labels: ♻️ 리팩토링

#338 Refactor: 상품 추가/수정에서 사용하는 공통된 스타일 분리
  src/Pages/Product/AddProduct.jsx
  src/Pages/Product/ProductModification.jsx
  src/Styles/ProductSharedStyles.jsx
Labels: ♻️ 리팩토링, 🎨 마크업 & 스타일링

#339 채팅페이지
  src/Api/Profile/FollowingListAPI.jsx
  src/Components/Chat/ChatList.jsx
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링

#340 Design: isWideView 일때, product & product skeleton image 크기 확대
  src/Components/common/ProductItem.jsx
  src/Components/common/Skeleton/ProductItemSkeleton.jsx
  src/Pages/Product/Product.jsx
Labels: 🎨 마크업 & 스타일링

#341 Input aria label, Side Nav
  src/Components/Chat/ChatContent.jsx
  src/Components/SideNav/SideNavBar.jsx
  src/Components/Sign/LoginForm.jsx
  src/Components/Sign/SignupForm.jsx
  src/Pages/Profile/UserProfileSetting.jsx
Labels: ♻️ 리팩토링, 🎨 마크업 & 스타일링

#342 Refactor: 이미지 레이지로딩 적용
  src/Pages/Product/LazyLoadedProductItem.jsx
  src/Pages/Product/Product.jsx
Labels: ♻️ 리팩토링

#345 프로필 페이지 내 에러 수정
  src/Components/Profile/MobileUser.jsx
  src/Components/Profile/PCUser.jsx
  src/Components/Profile/ProfileMain.jsx
  src/Components/Profile/UserProfile.jsx
  src/Hooks/useUserProfile.jsx
  src/Pages/Profile/Followers.jsx
  src/Pages/Profile/Profile.jsx
Labels: ♻️ 리팩토링, 🐞 버그

#346 My Pillowings slice 에러 관련
  src/Api/Profile/FollowingListAPI.jsx
  src/Components/Chat/ChatList.jsx
  src/Components/Home/MyPillowings.jsx
  src/Hooks/useFollowing.jsx
  src/Pages/Profile/Followers.jsx
Labels: ♻️ 리팩토링, 🐞 버그

#350 !HOTFIX: 이미지 수정시 여러 이미지 추가 안되는 에러 수정
  src/Api/Post/PostModifyAPI.jsx
  src/Pages/Post/PostModification.jsx
Labels: 🐞 버그

#351 Fix: 상품 카테고리 외화로 설정 안되는 오류 수정
  src/Components/common/Toggle.jsx
  src/Pages/Product/ProductModification.jsx
Labels: 🐞 버그

#352 Search 페이지
  src/Components/Search/SearchContent.jsx
  src/Components/Search/SearchModal.jsx
  src/Components/SideNav/SideNavBar.jsx
  src/Components/common/Header/SearchHeader.jsx
  src/Components/common/User.jsx
Labels: ✨ 기능 개발, ♻️ 리팩토링, 🎨 마크업 & 스타일링, 🐞 버그

#353 Fix: 상품 수정 시 카테고리가 용품으로 자동으로 바뀌는 현상 수정
  src/Pages/Product/AddProduct.jsx
  src/Pages/Product/Product.jsx
  src/Pages/Product/ProductModification.jsx
Labels: 🐞 버그

#355 PC 버전 프로필 유저 스켈레톤
  src/Components/Profile/UserProfile.jsx
  src/Components/common/Skeleton/PCProfileSkeleton.jsx
  src/Components/common/Skeleton/ProfileSkeleton.jsx
Labels: 🎨 마크업 & 스타일링

#356 프로필 포스트 무한스크롤
  src/Api/Post/GetPostAPI.jsx
  src/Components/Profile/ProfileMain.jsx
  src/Hooks/usePostInfinity.jsx
Labels: ✨ 기능 개발, ♻️ 리팩토링

#357 상품 staleTime 추가
  src/Pages/Product/Product.jsx
  src/Recoil/navbarIcon/navbarIcon.js
Labels: ♻️ 리팩토링, 🐞 버그
